modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/TheIllusiveC4/CuriousShulkerBoxes/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.curiousshulkerboxes]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiousshulkerboxes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2, 1.16)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiousshulkerboxes]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-2.0-beta2,)"
    ordering="NONE"
    side="BOTH"